### ISSUE TITLE
Brackets in strings are not ignored for the purpose of matching

### ISSUE THREAD

**Issue by szhorvat** [Fitzse/language-mathematica#1]
Brackets in strings are not ignored for the purpose of matching, i.e. if you put the cursor on the first `[` in

```
f["]"]
```

then Atom will highlight the one in the string as a match.

![image](https://cloud.githubusercontent.com/assets/1212871/9844881/2bfa6ae8-5ac7-11e5-8b6b-4a0888f5bfa6.png)

**Comment by Fitzse** [comment]
Yeah this is definitely annoying but I believe this currently is a bug in the [atom/bracket-matcher](https://github.com/atom/bracket-matcher) plugin. 
See: https://github.com/atom/bracket-matcher/issues/23 and https://github.com/atom/bracket-matcher/issues/78

I might take a stab at fixing the issue for the bracket-matcher if I get some time but I'm going to close this one out for now as there isn't anything to my knowledge I can do in the syntax definition to solve this problem.
